#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the setup-wizard-generator skill.
# Project: Mom's Dragonfly (Next.js 14 PWA + Convex + Vercel)
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env.local}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

ENV_FILE=".env.local"

banner "Mom's Dragonfly — Dev Environment Setup"

# ── Stage 1: Convex Deployment URL (public) ────────────────────────────────
stage "Convex: NEXT_PUBLIC_CONVEX_URL"
say "We'll grab your Convex deployment URL for the 'moms-dragonfly' project."
open_url "https://dashboard.convex.dev"
step "On the Convex dashboard, select the project named 'moms-dragonfly'."
step "Find and copy the deployment URL (starts with https://...convex.cloud — shown in Settings or on the dashboard overview)."
ask NEXT_PUBLIC_CONVEX_URL "Paste the Convex deployment URL:"
write_env NEXT_PUBLIC_CONVEX_URL "$NEXT_PUBLIC_CONVEX_URL"
# Convex CLI uses CONVEX_DEPLOYMENT to find the project; mirror it from the URL.
write_env CONVEX_DEPLOYMENT "$NEXT_PUBLIC_CONVEX_URL"

# Confirm CI secret will be set later (Stage 7); document it now.
note "This value will also be saved to GitHub secrets (Stage 7) and should be set in Vercel (Stage 8)."

# ── Stage 2: Google Places API Key (secret, server-side only) ───────────────
stage "Google Cloud: GOOGLE_PLACES_API_KEY"
say "Next: your Google Places API key (New Places API). It lives server-side in Convex, not in .env.local."
open_url "https://console.cloud.google.com/apis/credentials"
step "In Google Cloud Console → APIs & Services → Credentials, create (or reveal) an API Key."
step "Restrict it to 'Places API (New)' only. Copy the full key (starts AIza...)."
ask_secret GOOGLE_PLACES_API_KEY "Paste the Google Places API key:"
note "Writing this to Convex environment variables (not .env.local)."

# Execute convex env set directly; handle failure gracefully.
if printf '%s' "$GOOGLE_PLACES_API_KEY" | npx convex env set GOOGLE_PLACES_API_KEY >/dev/null 2>&1; then
  printf '  %s✓ set%s Convex env GOOGLE_PLACES_API_KEY\n' "$GREEN" "$RESET"
else
  SKIPPED+=("Convex env GOOGLE_PLACES_API_KEY (set manually: npx convex env set GOOGLE_PLACES_API_KEY ...)")
  warn "Convex env set for GOOGLE_PLACES_API_KEY failed. Ensure .env.local has CONVEX_DEPLOYMENT=<url> (Stage 1 writes this) or run `npx convex dev` first."
fi

# ── Stage 3: Brave Search API Key (optional, secret) ────────────────────────
stage "Brave Search: BRAVE_SEARCH_API_KEY (optional)"
say "Optional: Brave Search API key for entertainment events. Skip if you don't have one — the app falls back to Overpass data."
open_url "https://search.brave.com/api/"
step "If you have a Brave Search API subscription: go to the dashboard and reveal/copy your API token."

if confirm "Do you have a Brave Search API key to enter (y) or skip it (N)?"; then
  ask_secret BRAVE_SEARCH_API_KEY "Paste the Brave Search API key:"
  if [[ -n "${BRAVE_SEARCH_API_KEY:-}" ]]; then
    if printf '%s' "$BRAVE_SEARCH_API_KEY" | npx convex env set BRAVE_SEARCH_API_KEY >/dev/null 2>&1; then
      printf '  %s✓ set%s Convex env BRAVE_SEARCH_API_KEY\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("Convex env BRAVE_SEARCH_API_KEY (set manually)")
      warn "Convex env set for BRAVE_SEARCH_API_KEY failed. Ensure .env.local has CONVEX_DEPLOYMENT and `npx convex dev` has been run."
    fi
  else
    SKIPPED+=("Convex env BRAVE_SEARCH_API_KEY — left empty (optional)")
    note "Skipped — no key provided (optional)."
  fi
else
  SKIPPED+=("Convex env BRAVE_SEARCH_API_KEY — skipped by user (optional)")
  note "Skipped by user — Brave Search is optional; Overpass fallback will be used."
fi

# ── Stage 4: Gemini API Key (secret, server-side only) ───────────────────────
stage "Google AI Studio: GEMINI_API_KEY"
say "Next: Gemini Vision API key (used for OCR fallback on tickets). Server-side in Convex."
open_url "https://aistudio.google.com/app/apikey"
step "In Google AI Studio, get (or create) an API key. Copy it (starts AIza...)."
ask_secret GEMINI_API_KEY "Paste the Gemini API key:"

if printf '%s' "$GEMINI_API_KEY" | npx convex env set GEMINI_API_KEY >/dev/null 2>&1; then
  printf '  %s✓ set%s Convex env GEMINI_API_KEY\n' "$GREEN" "$RESET"
else
  SKIPPED+=("Convex env GEMINI_API_KEY (set manually: npx convex env set GEMINI_API_KEY ...)")
  warn "Convex env set for GEMINI_API_KEY failed. Ensure .env.local has CONVEX_DEPLOYMENT (<url>) and `npx convex dev` has run."
fi

# ── Stage 5: VAPID Keys for Web Push (generate + capture) ───────────────────
stage "Web Push: VAPID keys (generate + capture)"
say "Web push notifications need VAPID keys. We'll generate them with `npx web-push generate-vapid-keys`."
step "Open a terminal (or keep this wizard running) and run: npx web-push generate-vapid-keys"
step "Copy the output: you'll see a publicKey, a privateKey, and a subject line (mail:... or https://...)."

# Instruct user to run command manually; confirm they've done it.
if confirm "Have you run `npx web-push generate-vapid-keys` and have the keys ready?"; then
  ask VAPID_PUBLIC_KEY "Paste the publicKey value:"
  ask_secret VAPID_PRIVATE_KEY "Paste the privateKey value:"
  ask VAPID_SUBJECT "Paste the subject (e.g., mailto:you@example.com or https://momsdragonfly.app):"

  # Write all VAPID values to .env.local
  if [[ -n "${VAPID_PUBLIC_KEY:-}" ]]; then
    write_env VAPID_PUBLIC_KEY "$VAPID_PUBLIC_KEY"
  fi
  if [[ -n "${VAPID_PRIVATE_KEY:-}" ]]; then
    write_env VAPID_PRIVATE_KEY "$VAPID_PRIVATE_KEY"
  fi
  if [[ -n "${VAPID_SUBJECT:-}" ]]; then
    write_env VAPID_SUBJECT "$VAPID_SUBJECT"
  fi

  # Set private key and optional public/subject in Convex env
  if [[ -n "${VAPID_PRIVATE_KEY:-}" ]]; then
    if printf '%s' "$VAPID_PRIVATE_KEY" | npx convex env set VAPID_PRIVATE_KEY >/dev/null 2>&1; then
      printf '  %s✓ set%s Convex env VAPID_PRIVATE_KEY\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("Convex env VAPID_PRIVATE_KEY (set manually)")
      warn "Convex env set for VAPID_PRIVATE_KEY failed. Ensure .env.local has CONVEX_DEPLOYMENT (<url>) and `npx convex dev` has run."
    fi
  fi

  # VAPID_PUBLIC_KEY and VAPID_SUBJECT are used both in .env.local (for push API) and potentially in Convex
  if [[ -n "${VAPID_PUBLIC_KEY:-}" ]]; then
    if printf '%s' "$VAPID_PUBLIC_KEY" | npx convex env set VAPID_PUBLIC_KEY >/dev/null 2>&1; then
      printf '  %s✓ set%s Convex env VAPID_PUBLIC_KEY\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("Convex env VAPID_PUBLIC_KEY (optional, set manually if needed)")
      note "VAPID_PUBLIC_KEY set locally (.env.local); Convex env optional. Check .env.local has CONVEX_DEPLOYMENT if you want Convex to use it."
    fi
  fi

  if [[ -n "${VAPID_SUBJECT:-}" ]]; then
    if printf '%s' "$VAPID_SUBJECT" | npx convex env set VAPID_SUBJECT >/dev/null 2>&1; then
      printf '  %s✓ set%s Convex env VAPID_SUBJECT\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("Convex env VAPID_SUBJECT (optional, set manually if needed)")
      note "VAPID_SUBJECT set locally (.env.local); Convex env optional. Check .env.local has CONVEX_DEPLOYMENT if you want Convex to use it."
    fi
  fi
else
  SKIPPED+=("VAPID keys (user skipped generation step)")
  warn "VAPID keys skipped — push notifications will not work until keys are set."
fi

# ── Stage 6: Confirm Convex Environment Variables Set ───────────────────────
stage "Convex: Confirm env variables set"
say "Let's verify the Convex env variables were applied for this project."
note "Project in convex.json: $(cat convex.json 2>/dev/null | grep '"project"' || echo 'NOT FOUND — verify convex.json')"

if confirm "Did the previous `npx convex env set` steps complete without errors?"; then
  note "Great — server-side secrets (Google Places, Brave, Gemini, VAPID) are configured in Convex."
else
  SKIPPED+=("Convex env verification — review previous stages and run `npx convex env list` manually")
  warn "Some Convex env variables may not be set. Check with `npx convex env list` and re-run this wizard later if needed."
fi

# Optional: ask user to confirm `convex.json` project is correct.
if confirm "Is your Convex project `moms-dragonfly`? (If not, the wizard may have targeted the wrong project)"; then
  note "Confirmed: `moms-dragonfly` — the wizard applied env vars to the correct Convex project."
else
  warn "Convex project mismatch: verify `convex.json` has the correct project name before relying on env vars."
fi

# ── Stage 7: GitHub Secrets (CI pipeline) ───────────────────────────────────
stage "GitHub: CI secrets"
say "The CI pipeline (`.github/workflows/ci.yml`) needs two GitHub secrets."
step "Secret 1: NEXT_PUBLIC_CONVEX_URL — the value from Stage 1."
step "Secret 2: LHCI_GITHUB_APP_TOKEN — from the Lighthouse CI GitHub App (https://github.com/apps/lhci)."

# Re-use the NEXT_PUBLIC_CONVEX_URL value captured earlier for the secret
if [[ -n "${NEXT_PUBLIC_CONVEX_URL:-}" ]]; then
  set_secret NEXT_PUBLIC_CONVEX_URL "$NEXT_PUBLIC_CONVEX_URL"
else
  SKIPPED+=("GitHub secret NEXT_PUBLIC_CONVEX_URL — NEXT_PUBLIC_CONVEX_URL not set; set manually: gh secret set NEXT_PUBLIC_CONVEX_URL ...")
  warn "NEXT_PUBLIC_CONVEX_URL missing — cannot set CI secret. Ensure Stage 1 completed."
fi

# LHCI token: ask user to paste it (it's a secret token from Lighthouse CI app)
if confirm "Do you have the LHCI_GITHUB_APP_TOKEN from the Lighthouse CI GitHub App?"; then
  ask_secret LHCI_GITHUB_APP_TOKEN "Paste the LHCI_GITHUB_APP_TOKEN:"
  if [[ -n "${LHCI_GITHUB_APP_TOKEN:-}" ]]; then
    set_secret LHCI_GITHUB_APP_TOKEN "$LHCI_GITHUB_APP_TOKEN"
  else
    SKIPPED+=("GitHub secret LHCI_GITHUB_APP_TOKEN — left empty")
    warn "LHCI token not provided; Lighthouse CI will fail in CI."
  fi
else
  SKIPPED+=("GitHub secret LHCI_GITHUB_APP_TOKEN — user skipped (set manually when Lighthouse CI App is installed)")
  note "Skipped — set LHCI_GITHUB_APP_TOKEN manually via `gh secret set LHCI_GITHUB_APP_TOKEN ...` once the Lighthouse CI GitHub App is installed."
fi

# ── Stage 8: Confirm Vercel Environment Variables (documentation) ────────────
stage "Vercel: Confirm env variables (documentation)"
say "Finally: confirm your Vercel project has NEXT_PUBLIC_CONVEX_URL set."
note "The wizard doesn't call the Vercel CLI directly — you'll set this manually or confirm it below."

if confirm "Is NEXT_PUBLIC_CONVEX_URL already set in your Vercel project (Project Settings → Environment Variables)?"; then
  note "✓ Confirmed — Vercel env is configured."
else
  say "Go to Vercel Dashboard → Project 'moms-dragonfly' (or the deployed project) → Settings → Environment Variables."
  say "Add: NEXT_PUBLIC_CONVEX_URL = <the value from Stage 1>."
  say "Also confirm VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT are set if using web push in production."
  SKIPPED+=("Vercel env variables — confirm manually in Vercel dashboard")
  warn "Vercel environment variables must be set manually (this wizard does not call Vercel CLI)."
fi

# ──────────────────────────────────────────────────────────────────────────
# End of stages
# ──────────────────────────────────────────────────────────────────────────
finish
